deathRecordMsg: "\n<c:#ff527a><c:#ffc252>[!]</c:#ffc252> Você morreu em <c:#ff7552><b>%x %y %z</b></c:#ff7552> no <c:#ff7552><i>%d</i></c:#ff7552>!</c:#ff527a>\n"
dcWebhook:
  id: ""
  token: ""
  start: ":green_heart: O servidor **abriu** :)"
  stop: ":broken_heart: O servidor **fechou** :("
  join: "%p entrou no servidor."
  leave: "%p saiu do servidor."
welcomeMsg: "<rainbow>Seja bem vindo(a) ao servidor!</rainbow>"
bedMsgs: [
  "%p foi para a cama.",
  "%p está confortável em sua cama.",
  "%p foi dormir."
]