name: grill
description: $description
version: '${version}'

main: me.lukiiy.grill.Grill
api-version: '26.2'
load: POSTWORLD

authors: [ Lukiiy ]
folia-supported: true

dependencies:
  server:
    Geyser-Spigot:
      load: AFTER
      required: true